version: '3.8'
services:
  pgdb:
    image: postgres:15.6-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - monitoring

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    restart: always
    ports:
      - '9187:9187'
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@pgdb:5432/postgres?sslmode=disable"
    depends_on:
       - pgdb
       - prometheus
    networks:
      - monitoring


  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../prometheus_data:/prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

