version: '3.8'
services:
  pgdb:
    image: postgres:15.6-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'